db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://ecommerce-db.cnom46wiqyln.ap-south-2.rds.amazonaws.com:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=admin
db.password=MyDB#2026
stripe.secret.key=sk_test_your_key
stripe.publishable.key=pk_test_your_key
